# Generated by Django 5.0.7 on 2024-08-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0002_rename_vehicle_type_newentry_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newentry',
            name='oil_companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.oil_companies'),
        ),
    ]
