# Generated by Django 5.0.7 on 2024-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0003_oil_companies_newentry_oil_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='ac_filter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='air_filter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='oil_quantity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
