# Generated by Django 5.0.7 on 2024-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0005_newentry_oil_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='oil_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
