# Generated by Django 5.0.7 on 2024-08-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0007_body_parts_cng_parts_decoration_kabli_parts_silencer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil_companies',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oil_companies',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oil_companies',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='body_parts',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='body_parts',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cng_parts',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cng_parts',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kabli_parts',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kabli_parts',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='silencer',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='silencer',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spare_parts',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spare_parts',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
