# Generated by Django 5.0.7 on 2024-08-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0008_oil_companies_profit_oil_companies_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='body_parts',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cng_parts',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decoration',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kabli_parts',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silencer',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spare_parts',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
