# Generated by Django 5.0.7 on 2024-08-21 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0009_body_parts_profit_cng_parts_profit_decoration_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('Spare Parts', 'Spare Parts'), ('Body Parts', 'Body Parts'), ('CNG Parts', 'CNG Parts'), ('Kabli Parts', 'Kabli Parts'), ('Silencer', 'Silencer'), ('Decoration', 'Decoration'), ('Oil Companies', 'Oil Companies'), ('Oil Filter', 'Oil Filter'), ('A/C Filter', 'A/C Filter'), ('Air Filter', 'Air Filter')], max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, choices=[('Spare Parts', 'Spare Parts'), ('Body Parts', 'Body Parts'), ('CNG Parts', 'CNG Parts'), ('Kabli Parts', 'Kabli Parts'), ('Silencer', 'Silencer'), ('Decoration', 'Decoration'), ('Oil Companies', 'Oil Companies'), ('Oil Filter', 'Oil Filter'), ('A/C Filter', 'A/C Filter'), ('Air Filter', 'Air Filter')], max_length=50, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=10, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=10, null=True)),
                ('profit', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='body_parts',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='cng_parts',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='kabli_parts',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='silencer',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='spare_parts',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='ac_filter',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='air_filter',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='oil_filter',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='oil_price',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='oil_quantity',
        ),
        migrations.AddField(
            model_name='newentry',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.product'),
        ),
        migrations.DeleteModel(
            name='Body_Parts',
        ),
        migrations.DeleteModel(
            name='CNG_Parts',
        ),
        migrations.DeleteModel(
            name='Decoration',
        ),
        migrations.DeleteModel(
            name='Kabli_Parts',
        ),
        migrations.DeleteModel(
            name='Silencer',
        ),
        migrations.DeleteModel(
            name='Spare_Parts',
        ),
    ]
