# Generated by Django 5.0.7 on 2024-08-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0010_product_remove_newentry_body_parts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body_Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CNG_Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kabli_Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Silencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spare_Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='newentry',
            name='ac_filter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='air_filter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='oil_filter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='oil_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='oil_quantity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='body_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.body_parts'),
        ),
        migrations.AddField(
            model_name='newentry',
            name='cng_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.cng_parts'),
        ),
        migrations.AddField(
            model_name='newentry',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.decoration'),
        ),
        migrations.AddField(
            model_name='newentry',
            name='kabli_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.kabli_parts'),
        ),
        migrations.AddField(
            model_name='newentry',
            name='silencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.silencer'),
        ),
        migrations.AddField(
            model_name='newentry',
            name='spare_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OilTraders.spare_parts'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
