# Generated by Django 5.0.7 on 2024-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0011_body_parts_cng_parts_decoration_kabli_parts_silencer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='testEntry',
            field=models.JSONField(default={}, null=True),
        ),
    ]
