# Generated by Django 5.0.7 on 2024-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0012_newentry_testentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newentry',
            name='testEntry',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
