# Generated by Django 5.0.7 on 2024-08-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0013_alter_newentry_testentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newentry',
            old_name='testEntry',
            new_name='bodyPartEntry',
        ),
        migrations.AddField(
            model_name='newentry',
            name='cngPartEntry',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='decorationEntry',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='kabliPartEntry',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='silencerEntry',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='newentry',
            name='sparePartEntry',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
