# Generated by Django 5.0.7 on 2024-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0014_rename_testentry_newentry_bodypartentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AC_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Air_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oil_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='oil_price',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='oil_quantity',
        ),
        migrations.AlterField(
            model_name='newentry',
            name='ac_filter',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='air_filter',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='oil_companies',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='newentry',
            name='oil_filter',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
