# Generated by Django 5.0.7 on 2024-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0016_whole_sale_newentry_wholesaleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_filter',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='air_filter',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='body_parts',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cng_parts',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='decoration',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kabli_parts',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oil_companies',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oil_filter',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='silencer',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spare_parts',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whole_sale',
            name='rack_no',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
