# Generated by Django 5.0.7 on 2024-09-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0017_ac_filter_rack_no_air_filter_rack_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_filter',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='air_filter',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='body_parts',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cng_parts',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='decoration',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kabli_parts',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oil_companies',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oil_filter',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='silencer',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spare_parts',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whole_sale',
            name='total_products',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
