# Generated by Django 5.0.7 on 2024-09-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0018_ac_filter_total_products_air_filter_total_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac_filter',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='air_filter',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='body_parts',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cng_parts',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kabli_parts',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oil_companies',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oil_filter',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='silencer',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spare_parts',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whole_sale',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
