# Generated by Django 5.0.7 on 2024-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OilTraders', '0021_alter_ac_filter_total_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='labour',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
